port: 4000
auth0:
  id: 'insta-shop'
  app:
    clientID: 'D3YH7UPhP9GkinKMj4X2SEVTRpvvW56i'
    redirectUri: 'http://localhost:4000/callback'
    audience: 'http://localhost:4000/ig'
    responseType: 'token id_token'
    scope: 'read:users read:user_idp_tokens openid profile'
  server:
    client_id: '86bvBejYoJua5a4jOJaSmbyMPWUdPQvU'
    client_secret: 't6VrBXy8rJMYEfQbScSeUeC858qCT0AmC92ufjFBFSs6Ju-gG_c2x7m7FlhIJ9Xo'
    grant_type: 'client_credentials'
